test_flask/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, FileField
from wtforms.validators import DataRequired
from flask_wtf.file import FileAllowed


class PostForm(FlaskForm):
    title = StringField('Заголовок', validators=[DataRequired()])
    content = TextAreaField('Текст поста', validators=[DataRequired()])
    submit = SubmitField('Отправить')
    picture = FileField('Приложите фото к посту',
                        validators=[FileAllowed(['jpg', 'png'])])


class CommentForm(FlaskForm):
    comment = StringField('Комментарий', validators=[DataRequired()])

test_flask/posts/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from flask_login import current_user, login_required
from test_flask import db
from test_flask.models import Post, Comment
from test_flask.posts.forms import PostForm, CommentForm
from test_flask.users.utils import save_posts_pictures

posts = Blueprint('posts', __name__)


@posts.route("/allpost")
@login_required
def allpost():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('allpost.html', posts=posts)


@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    picture_name = None
    if form.validate_on_submit():
        if form.picture.data:
            picture_name = save_posts_pictures(form.picture.data)
        post = Post(title=form.title.data, content=form.content.data,
                    author=current_user, image_file=picture_name)
        db.session.add(post)
        db.session.commit()
        flash('Ваш пост создан!', 'success')
        return redirect(url_for('posts.allpost'))
    return render_template('create_post.html',
                           title='Новый пост', form=form, image_file=picture_name, legend='Новый пост')


@posts.route("/post/<int:post_id>", methods=['GET', 'POST'])
def post(post_id):
    post = Post.query.get_or_404(post_id)
    form = CommentForm()
    if form.validate_on_submit():
        comment = Comment(body=form.comment.data, post_id=post_id,
                          username=current_user.username)
        db.session.add(comment)
        db.session.commit()
        flash('Ваш комментарий добавлен!', 'success')
        return redirect(f'/post/{post_id}')
    return render_template('post.html', title=post.title, post=post, form=form)


@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_posts_pictures(form.picture.data)
            post.image_file = picture_file
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Ваш пост обновлен!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
        image_file = url_for('static', filename='food_pics/' +
                                                post.image_file)
    return render_template('create_post.html', title='Обновление поста',
                           form=form,  image_file=image_file, legend='Обновление поста')


@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Ваш пост был удален!', 'success')
    return redirect(url_for('posts.allpost'))


@posts.route("/comment/<int:comment_id>/delete", methods=['POST'])
@login_required
def delete_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    if comment.username != current_user.username:
        abort(403)
    db.session.delete(comment)
    db.session.commit()
    flash('Ваш комментарий был удален!', 'success')
    return redirect(url_for('posts.post', post_id=comment.post_id))

test_flask/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from test_flask import db, bcrypt
from test_flask.models import User, Post
from test_flask.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm
from test_flask.users.utils import send_reset_email
from test_flask.users.utils import save_picture

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data,
                    email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Ваша учетная запись была создана!'
              ' Теперь вы можете войти в систему', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('posts.allpost'))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password,
                                               form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('posts.allpost'))
        else:
            flash('Войти не удалось. Пожалуйста, '
                  'проверьте электронную почту и пароль', 'внимание')
    return render_template('login.html', title='Авторизация', form=form)


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Ваш аккаунт был обновлен!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
        page = request.args.get('page', 1, type=int)
        user = User.query.filter_by(username=form.username.data).first_or_404()
        posts = Post.query.filter_by(author=user).order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account', image_file=image_file, form=form, posts=posts, user=user)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user).order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)

@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('posts.allposts'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('На почту отправлено письмо с '
              'инструкциями по сбросу пароля.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html',
                           title='Сброс пароля', form=form)

@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('posts.allpost'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('Это недействительный или просроченный токен', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.\
            generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Ваш пароль был обновлен! '
              'Теперь вы можете авторизоваться', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html',
                           title='Сброс пароля', form=form)

test_flask/templates/account.html
{% extends "layout.html" %}

{% block head %}
  <style>
    .container{
      margin-bottom: 0.8rem;
    }

    .content-section{
      box-shadow: 10px 20px 8px darkslategray;
    }

    .card{
      border-radius: 25px;
      /* border-top-right-radius: 25px;
      border-bottom-left-radius: 25px; */
      background-color:  white; 
      box-shadow: 10px 15px 10px #4a4e69;
      width: 92%;
    }

    a{
      color: #003049;
    }

    small{
      color: lightslategray;
    }

    p{
      color: rgb(43, 37, 37);
    }
    
    /* i{
      padding: 0px 7px;
      cursor: pointer;
    } */
  </style>
{% endblock head %}


{% block content %}
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ image_file }}">
        <div class="media-body">
          <h2 class="account-heading">{{ current_user.username }}</h2>
          <p class="text-secondary">{{ current_user.email }}</p>
        </div>
      </div>

      <form method="POST" action="" enctype="multipart/form-data">
          {{ form.hidden_tag() }}
          <fieldset class="form-group">
              <legend class="border-bottom mb-4">Аккаунт пользователя</legend>
              <div class="form-group">
                  {{ form.username.label(class="form-control-label") }}

                  {% if form.username.errors %}
                      {{ form.username(class="form-control form-control-lg is-invalid") }}
                      <div class="invalid-feedback">
                          {% for error in form.username.errors %}
                              <span>{{ error }}</span>
                          {% endfor %}
                      </div>
                  {% else %}
                      {{ form.username(class="form-control form-control-lg") }}
                  {% endif %}
              </div>
              <div class="form-group">
                  {{ form.email.label(class="form-control-label") }}
                  {% if form.email.errors %}
                      {{ form.email(class="form-control form-control-lg is-invalid") }}
                      <div class="invalid-feedback">
                          {% for error in form.email.errors %}
                              <span>{{ error }}</span>
                          {% endfor %}
                      </div>
                  {% else %}
                      {{ form.email(class="form-control form-control-lg") }}
                  {% endif %}
              </div>
              <div class="form-group">
                  {{ form.picture.label() }}
                  {{ form.picture(class="form-control-file") }}
                  {% if form.picture.errors %}
                      {% for error in form.picture.errors %}
                          <span class="text-danger">{{ error }}</span></br>
                      {% endfor %}
                  {% endif %}
              </div>
          </fieldset>
          <div class="form-group">
              {{ form.submit(class="btn btn-outline-info") }}
          </div>
      </form>      
    </div>   



{% endblock content %}

test_flask/templates/allpost.html
{% extends "layout.html" %}

{% block head %}
<style>
    body{
      background-image: url('../static/images/bck_posts.jpg');
      /* background-repeat: no-repeat; */
        /* background-position: 50% 0; */
        background-size: cover;
      }

    .card{
      border-radius: 25px;
      /* border-top-right-radius: 25px;
      border-bottom-left-radius: 25px; */
      background-color:  white; 
      box-shadow: 10px 15px 10px #4a4e69;
      width: 92%;
    }

    .card-title{
      margin-bottom: 0 !important;

    }

    a{
      color: #003049 !important;
      text-decoration: none;
    }

    small{
      color: lightslategray;
    }

    p{
      color: rgb(43, 37, 37);
    }

    /* i{
      padding: 0px 7px;
      cursor: pointer;
    } */

</style>
{% endblock head %}

{% block content %}
{% for post in posts.items %}
<div class="container" style="display: flex;">
    <article class="media" style="display: flex; flex-direction: column;">
        <img class="rounded-circle article-img" style="margin-right: 5px; border: solid;"
             src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
        <a href="{{ url_for('users.user_posts', username=post.author.username) }}" id="author" style="margin: 0 auto; font-weight: bold;">{{
            post.author.username }}</a>
    </article>

    <div class="card" style="margin-bottom: 20px;">
        <div class="card-body">
            <h3 class="card-title"><a class="title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title
                }}</a></h3>

            <small>Опубликовано {{ post.date_posted.strftime('%A, %d %B %Y %H:%M') }}</small>
            <br>
            <br>
            {% if post.image_file %}
            <div class="form-group" style="text-align: center">
                <img style="margin-right: 5px;" src="{{ url_for('static',
                  filename='food_pics/' + post.image_file) }}">
            </div>
            {% endif %}
            <pre><p class="card-text">{{ post.content }}</p></pre>
        </div>
        <!-- <div class="card-footer" style="font-size: 20px;">
          <i class="fa fa-heart-o"></i>
          <i class="fa fa-bookmark-o"></i>
        </div> -->
    </div>
</div>
{% endfor %}

{% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
{% if page_num %}
{% if posts.page == page_num %}
<a class="btn btn-success mb-4" href="{{ url_for('posts.allpost', page=page_num) }}">{{ page_num }}</a>
{% else %}
<a class="btn btn-outline-success mb-4" href="{{ url_for('posts.allpost', page=page_num) }}">{{ page_num }}</a>
{% endif %}
{% else %}
...
{% endif %}
{% endfor %}
{% endblock content %}

test_flask/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Alice&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap" rel="stylesheet">

    {% if title %}
    <title>Нейроварево - {{ title }}</title>
    {% else %}
    <title>Нейроварево</title>
    {% endif %}

    {% block head %} {% endblock head %}

    <style>
        .card-text{
        font-size: 1.05rem;
        font-family: 'Tangerine', serif;
        font-optical-sizing: auto;
        }

        body{
          background-color: #e5e5e5;
          margin-top: 6.5rem;
        }

        .navigation-links{
          color: black !important;
          font-weight: 500;
          background-color: rgb(183, 214, 252);
          border-radius: 5px;
          border-bottom: 4px solid blue;
          margin: 5px;
          background-size: 200% 200%;
          background-image: linear-gradient( transparent 50%, rgb(79, 128, 233) 50%);
          transition: background-position 300ms, color 300ms ease, border-color 300ms ease;
        }

        .navigation-links:hover{
          color: white;
          background-image: linear-gradient( transparent 50%, #3a86ff 50%);
          background-position: 0% 100%;
        }

        .navbar{
          background-color: #c6def1;
          box-shadow: 0px 1px 10px black;
        }

        .navbar .container{
          margin-bottom: 0;
        }
        .names{
          color: black;
          text-align: center;
          margin-right: 30px;
          margin-top: 12px;
        }
    </style>


    {% block style %} {% endblock style %}
</head>
<body>
<header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark fixed-top">
        <div class="container">
            <a class="navbar-brand mr-4" href="/"
               style="color: rgb(7, 85, 173); font-family: 'Lobster', cursive; font-weight: 800; font-size: 30px; ">Нейроварево</a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                    aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            {% if current_user.is_authenticated %}
            <h4 class="names">Привет, {{ current_user.username }}!</h4>
            <a class="nav-item nav-link navigation-links" href="{{ url_for('users.account') }}"><i
                    class="fa fa-user"></i>Профиль</a>
            <a class="nav-item nav-link navigation-links" href="{{ url_for('posts.new_post') }}"><i
                    class="fa fa-plus"></i> Новый пост</a>

            <a class="nav-item nav-link navigation-links" href="{{ url_for('posts.allpost') }}"><i class="fa fa-th"></i>
                Все записи</a>
            <a class="nav-item nav-link navigation-links" href="{{ url_for('users.logout') }}"><i
                    class="fa fa-sign-out"></i>Выйти</a>
            {% else %}
            <a class="nav-link nav-item navigation-links" href="{{ url_for('users.login') }}">Войти</a>
            <a class="nav-link nav-item navigation-links" href="{{ url_for('users.register') }}">Зарегистрироваться</a>
            {% endif %}
            <div class="collapse navbar-collapse" id="navbarToggle" style="justify-content: flex-end;">
                <!-- Navbar Right Side -->

            </div>
        </div>
    </nav>
</header>

<main role="main" class="container">
    <div class="row">
        <div class="col-md-10">
            {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
            {% for category, message in messages %}
            <div class="alert alert-{{ category }}">
                {{ message }}
            </div>
            {% endfor %}
            {% endif %}
            {% endwith %}

            {% block content %}{% endblock %}
        </div>
    </div>
</main>


<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>
</html>

test_flask/templates/login.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section" style="box-shadow: 10px 15px 10px #4a4e69;">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Авторизация</legend>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                {{ form.email(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.email(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {% if form.password.errors %}
                {{ form.password(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-check">
                {{ form.remember(class="form-check-input") }}
                {{ form.remember.label(class="form-check-label") }}
            </div>
        </fieldset>


        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
            <small class="text-muted ml-2">
                <a href="{{ url_for('users.reset_request') }}">Забыли пароль?</a>
            </small>

        </div>
        <small style="font-size: 15px; font-weight: 500;">
            Нужен аккаунт? <a class="ml-2" href="{{ url_for('users.register') }}">Зарегистрируйтесь</a>
        </small>
    </form>
</div>
{% endblock content %}

test_flask/templates/post.html
{% extends "layout.html" %}

{% block head %}
<style>
    .container{
      margin-bottom: 0.8rem;
    }

    .card{
      border-radius: 25px;
      /* border-top-right-radius: 25px;
      border-bottom-left-radius: 25px; */
      background-color:  white; 
      box-shadow: 10px 15px 10px #4a4e69;
      width: 92%;
    }
    
    .card-title{
      margin-bottom: 0 !important;

    }

    a{
      color: #003049 !important;
      text-decoration: none;
    }

    small{
      color: lightslategray;
    }

    p{
      color: rgb(43, 37, 37);
    }

    /* i{
      padding: 0px 7px;
      cursor: pointer;
    } */
</style>
{% endblock head %}

{% block content %}
<div class="container" style="display: flex;">
    <article class="media" style="display: flex; flex-direction: column;">
        <img class="rounded-circle article-img" style="margin-right: 5px; border: solid;"
             src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
        <a href="{{ url_for('users.user_posts', username=post.author.username) }}" id="author"
           style="margin: 0 auto; font-weight: bold;">{{
            post.author.username }}</a>
    </article>


    <div class="card" style="margin-bottom: 20px;">
        <div class="card-body">
            <h3 class="card-title">{{ post.title }}</h3>
            <small>Опубликовано {{ post.date_posted.strftime('%A, %d %B %Y %I:%M') }}</small>
            <br>
            <br>
            {% if post.image_file %}
            <div class="form-group" style="text-align: center">
                <img style="margin-right: 5px;" src="{{ url_for('static',
                  filename='food_pics/' + post.image_file) }}">
            </div>
            {% endif %}
            <pre class="card-text">{{ post.content }}</pre>
        </div>
        <div class="card-footer" style="font-size: 20px;">
            <!-- <i class="fa fa-heart-o"></i>
            <i class="fa fa-bookmark-o"></i> -->
            {% if post.author == current_user %}
            <div class="card-footer" style="font-size: 20px;"> {% if post.author == current_user %}<a
                    class="btn btn-secondary btn-sm mt-1 mb-1" style="background: #5fba69; color: #fff"
                    href="{{url_for('posts.update_post', post_id=post.id) }}">Редактировать</a>
                <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">
                    Удалить
                </button>

                {% endif %}
            </div>


            {% endif %}
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Удалить пост?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
                    <input class="btn btn-danger" type="submit" value="Удалить">
                </form>
            </div>
        </div>
    </div>
</div>

{% if post.comments %}

<h2>Комментарии: </h2>
<p>{% for comment in post.comments | reverse %}
<p style="font-size: 18px;">{{ comment.body }}</p>
<p><small>Автор: {{ comment.username }}</small>
    <small>Дата: {{ comment.timestamp.strftime('%A, %d %B %Y %H:%M') }}</small></p>

{% if comment.username == current_user.username %}
<form action="{{ url_for('posts.delete_comment', comment_id=comment.id) }}" method="POST">
    <input class="submit" type="submit" value="Удалить">
</form>
{% endif %}
<hr>
{% endfor %}</p>

{% endif %}


<div id="content">
    <!-- insert the page content here -->
    <h2>Оставьте комментарий</h2>
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <div class="form_settings">

            <p><span></span><textarea name="comment" style="width: 100%; height: 150px"></textarea>
                {% if form.comment.errors %}
                {% for error in form.comment.errors %}
            <p style="color: red">{{ error }}</p>
            {% endfor %}
            {% endif %}
            </p>

            <p style="padding-top: 15px"><span>&nbsp;</span><input class="submit" type="submit" name="submit"
                                                                   value="Сохранить"/></p>
        </div>
    </form>
</div>
{% endblock content %}

test_flask/templates/user_posts.html
{% extends "layout.html" %}

{% block head %}
<style>
    .container{
      margin-bottom: 0.8rem;
    }

    .card{
      border-radius: 25px;
      /* border-top-right-radius: 25px;
      border-bottom-left-radius: 25px; */
      background-color:  white; 
      box-shadow: 10px 15px 10px #4a4e69;
      width: 92%;
    }
    
    .card-title{
      margin-bottom: 0 !important;

    }

    a{
      color: #003049 !important;
      text-decoration: none;
    }

    small{
      color: lightslategray;
    }

    p{
      color: rgb(43, 37, 37);
    }

    /* i{
      padding: 0px 7px;
      cursor: pointer;
    } */
</style>
{% endblock head %}

{% block content %}
<h1 class="mb-3">Посты опубликованы пользователем {{ user.username }} ({{ posts.total }})</h1>
{% for post in posts.items %}
<div class="container" style="display: flex;">
    <article class="media" style="display: flex; flex-direction: column;">
        <img class="rounded-circle article-img" style="margin-right: 5px; border: solid;"
             src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
        <a href="{{ url_for('users.user_posts', username=post.author.username) }}" id="author"
           style="margin: 0 auto; font-weight: bold;">{{
            post.author.username }}</a>
    </article>

    <div class="card" style="margin-bottom: 20px;">
        <div class="card-body">
            <h3 class="card-title">{{ post.title }}</h3>
            <small>Опубликовано {{ post.date_posted.strftime('%A, %d %B %Y %H:%M') }}</small>
            <br>
            <br>
            {% if post.image_file %}
            <div class="form-group" style="text-align: center">
                <img style="margin-right: 5px;" src="{{ url_for('static',
                  filename='food_pics/' + post.image_file) }}">
            </div>
            {% endif %}
            <pre class="card-text">{{ post.content }}</pre>
        </div>
        <!-- <div class="card-footer" style="font-size: 20px;">
          <i class="fa fa-heart-o"></i>
          <i class="fa fa-bookmark-o"></i>
        </div> -->
    </div>
</div>
{% endfor %}


{% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
{% if page_num %}
{% if posts.page == page_num %}
<a class="btn btn-success mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{
    page_num }}</a>
{% else %}
<a class="btn btn-outline-success mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{
    page_num }}</a>
{% endif %}
{% else %}
...
{% endif %}
{% endfor %}
{% endblock content %}